USE GranTorino
GO

CREATE TABLE [User] (
	[IdCard] NUMERIC(20) NOT NULL,
	[Username] VARCHAR(25) NOT NULL UNIQUE,
	[PasswordHash] BINARY(64) NOT NULL,
	[FirstName] VARCHAR(50) NOT NULL,
	[MiddleName] VARCHAR(50),
	[LastName] VARCHAR(50) NOT NULL,
	[SecondLastName] VARCHAR(50),
	[Salt] UNIQUEIDENTIFIER 
	CONSTRAINT PK_User PRIMARY KEY(IdCard)
);
GO

CREATE TABLE [Client] (
	[IdCard] NUMERIC(20) NOT NULL,
	[AccountNumber] NUMERIC(20) NOT NULL,
	CONSTRAINT PK_Client PRIMARY KEY(IdCard),
	CONSTRAINT FK_ClientId FOREIGN KEY (IdCard) REFERENCES [User]
);

CREATE TABLE [Owner] (
	[IdCard] NUMERIC(20) NOT NULL,
	CONSTRAINT PK_Owner PRIMARY KEY(IdCard),
	CONSTRAINT FK_OwnerId FOREIGN KEY (IdCard) REFERENCES [User]
);

CREATE TABLE [Admin] (
	[IdCard] NUMERIC(20) NOT NULL,
	CONSTRAINT PK_Admin PRIMARY KEY(IdCard),
	CONSTRAINT FK_AdminId FOREIGN KEY (IdCard) REFERENCES [User]
);